name: DobbyApp
options:
  bundleIdPrefix: com.dobby
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: 1.15.0

targets:
  DobbyApp:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: DobbyApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dobby.DobbyApp
        PRODUCT_NAME: Dobby
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_CFBundleDisplayName: Dobby
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2024"
        SWIFT_EMIT_LOC_STRINGS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        COMBINE_HIDPI_IMAGES: true
        GENERATE_INFOPLIST_FILE: true
    entitlements:
      path: DobbyApp/DobbyApp.entitlements
      properties:
        com.apple.security.app-sandbox: false

  DobbyAppTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: DobbyAppTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: DobbyApp
      - package: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dobby.DobbyApp.Tests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Dobby.app/Contents/MacOS/Dobby"
        BUNDLE_LOADER: "$(TEST_HOST)"
        SWIFT_VERSION: "5.9"

  DobbyAppUITests:
    type: bundle.ui-testing
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: DobbyAppUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: DobbyApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dobby.DobbyApp.UITests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: DobbyApp
        SWIFT_VERSION: "5.9"

schemes:
  DobbyApp:
    build:
      targets:
        DobbyApp: all
        DobbyAppTests: [test]
        DobbyAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - DobbyAppTests
        - DobbyAppUITests
